### ISSUE TITLE
Is there a way to implement a layer with pixelized refractive index distribution in S4?

### ISSUE THREAD

**Issue by OmerYesilyurt1** [pyMatJ/S4Utils#1]

**Comment by pyMatJ** [comment]
Hi Omer,
1°) Opening an issue on a repo about another repo is not really a standard way to get an answer. This repo is a bunch of utility functions to help with S4, not S4 in itself
2°) not describing the problem in more details than just the title does not help. What does "pixelized" mean?
3°) politeness also goes a long way. Try adding short formulas like "hello"...

4°) no, I don't think this is possible. A layer is a homogeneous material. Depending on what you want to achieve you could use an effective medium theory to extract an effective index.

**Comment by OmerYesilyurt1** [comment]
Hi Mat,

Thank you for the kind and detailed comment. This is what I mean with pixelized refractive index distribution:

![image](https://user-images.githubusercontent.com/101416038/158425759-23beb093-b4b7-4fee-b9e9-2f817ad5c0d5.png)

We are looking at a complex structure from above. This is the refractive index distribution of the layer.

Best,
Omer

**Comment by pyMatJ** [comment]
Hi Omer,
considering the complexity and non-periodicity of the structure, S4 (and more generally RCWA/FMM methods) is really not adapted.
These methods split the electromagnetic problem: each layer is assumed to be homogeneous. Propagation/diffraction in each layer is done using Fourier transform to project the field on eigenmodes of each layer. “Junction” between layers in the z direction is done using scattering matrices. This works because the problem is periodic in the plane.

Take a look at other methods. Especially Meep if you are looking for something python-interfaced.

**Comment by OmerYesilyurt1** [comment]
Hi Mat,

I see. Thanks for the quick and great help!
